APPLICATION_NAME = mimportplugin

$(APPLICATION_NAME)_FILES = mimportplugin.mm
$(APPLICATION_NAME)_FRAMEWORKS = UIKit #QuartzCore CoreGraphics
$(APPLICATION_NAME)_CFLAGS = -fobjc-arc
$(APPLICATION_NAME)_LDFLAGS = -Wl,-segalign,4000

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk